use crate::include_models;
include_models!(lrn_default_size3, lrn_custom_size3, lrn_custom_size2);

#[cfg(test)]
mod tests {
    use super::*;
    use burn::tensor::{Tensor, TensorData, Tolerance, ops::FloatElem};

    use crate::backend::TestBackend;
    type FT = FloatElem<TestBackend>;

    // Input shared by both tests — generated with np.random.seed(42), shape [1, 5, 3, 3]
    fn test_input(
        device: &<TestBackend as burn::tensor::backend::Backend>::Device,
    ) -> Tensor<TestBackend, 4> {
        Tensor::<TestBackend, 4>::from_floats(
            [[
                [
                    [0.49671414, -0.13826430, 0.64768857],
                    [1.52302980, -0.23415338, -0.23413695],
                    [1.57921280, 0.76743470, -0.46947438],
                ],
                [
                    [0.54256004, -0.46341768, -0.46572974],
                    [0.24196227, -1.91328020, -1.72491790],
                    [-0.56228750, -1.01283110, 0.31424734],
                ],
                [
                    [-0.90802410, -1.41230370, 1.46564880],
                    [-0.22577630, 0.06752820, -1.42474820],
                    [-0.54438275, 0.11092259, -1.15099360],
                ],
                [
                    [0.37569803, -0.60063870, -0.29169375],
                    [-0.60170660, 1.85227820, -0.01349723],
                    [-1.05771090, 0.82254493, -1.22084370],
                ],
                [
                    [0.20886360, -1.95967010, -1.32818600],
                    [0.19686124, 0.73846656, 0.17136829],
                    [-0.11564828, -0.30110368, -1.47852200],
                ],
            ]],
            device,
        )
    }

    #[test]
    fn lrn_with_odd_size_attr() {
        // Model: size=3, alpha=0.0001, beta=0.75, bias=1.0
        // Input/output generated by lrn.py using np.random.seed(42)
        let device = Default::default();
        let model: lrn_default_size3::Model<TestBackend> = lrn_default_size3::Model::default();

        let output = model.forward(test_input(&device));

        let expected = TensorData::from([[
            [
                [0.49670744, -0.13826350, 0.64767830],
                [1.52293920, -0.23413163, -0.23411924],
                [1.57910190, 0.76740370, -0.46947062],
            ],
            [
                [0.54254156, -0.46339187, -0.46569732],
                [0.24194759, -1.91310240, -1.72469970],
                [-0.56224380, -1.01279000, 0.31423440],
            ],
            [
                [-0.90799550, -1.41221300, 1.46555900],
                [-0.22577363, 0.06751623, -1.42456980],
                [-0.54435920, 0.11091784, -1.15090980],
            ],
            [
                [0.37568858, -0.60054570, -0.29166460],
                [-0.60169990, 1.85209390, -0.01349653],
                [-1.05767320, 0.82252896, -1.22069120],
            ],
            [
                [0.20886263, -1.95946430, -1.32812460],
                [0.19685927, 0.73839310, 0.17136817],
                [-0.11564501, -0.30109790, -1.47838600],
            ],
        ]]);

        output
            .to_data()
            .assert_approx_eq::<FT>(&expected, Tolerance::default());
    }

    #[test]
    fn lrn_with_custom_params_odd_size() {
        // Model: size=3, alpha=0.1, beta=0.5, bias=0.5
        // Input/output generated by lrn.py using np.random.seed(42)
        let device = Default::default();
        let model: lrn_custom_size3::Model<TestBackend> = lrn_custom_size3::Model::default();

        let output = model.forward(test_input(&device));

        let expected = TensorData::from([[
            [
                [0.69012270, -0.19402850, 0.89713633],
                [2.00109200, -0.29645630, -0.30201660],
                [2.04959630, 1.03122810, -0.65698440],
            ],
            [
                [0.73458560, -0.61151880, -0.60488580],
                [0.31744632, -2.42206600, -2.10941890],
                [-0.72377340, -1.36047200, 0.42189476],
            ],
            [
                [-1.23338130, -1.84544590, 1.92172560],
                [-0.31439218, 0.07868423, -1.74471620],
                [-0.72895460, 0.14860424, -1.48948900],
            ],
            [
                [0.51429660, -0.71457910, -0.36655736],
                [-0.83840940, 2.32867720, -0.01789874],
                [-1.42931820, 1.13415650, -1.49517450],
            ],
            [
                [0.29357510, -2.44951920, -1.77227190],
                [0.27475724, 0.92850890, 0.24211301],
                [-0.15770810, -0.41533524, -1.87387590],
            ],
        ]]);

        output
            .to_data()
            .assert_approx_eq::<FT>(&expected, Tolerance::default());
    }

    #[test]
    fn lrn_with_custom_params_even_size() {
        // Model: size=2, alpha=0.1, beta=0.5, bias=0.5
        // Input/output generated by lrn.py using np.random.seed(42)
        let device = Default::default();
        let model: lrn_custom_size2::Model<TestBackend> = lrn_custom_size2::Model::default();

        let output = model.forward(test_input(&device));

        let expected = TensorData::from([[
            [
                [0.68419300, -0.19328806, 0.88814480],
                [1.93595500, -0.28275487, -0.29007486],
                [1.97323910, 1.00704970, -0.65358907],
            ],
            [
                [0.72766640, -0.59311813, -0.59231320],
                [0.34032774, -2.31465130, -1.99141510],
                [-0.77190554, -1.36334030, 0.41580173],
            ],
            [
                [-1.22629520, -1.79686420, 1.87402190],
                [-0.31289953, 0.08238979, -1.83704020],
                [-0.72057533, 0.15172908, -1.43788600],
            ],
            [
                [0.52647560, -0.71280000, -0.37896428],
                [-0.83438460, 2.21577480, -0.01905982],
                [-1.41772800, 1.12104320, -1.47634470],
            ],
            [
                [0.29473555, -2.35572770, -1.73178890],
                [0.27786592, 1.01698770, 0.24199627],
                [-0.16344210, -0.42390760, -1.89413850],
            ],
        ]]);

        output
            .to_data()
            .assert_approx_eq::<FT>(&expected, Tolerance::default());
    }
}
