use crate::include_models;
include_models!(lrn_size3, lrn_size2, lrn_non_default);

#[cfg(test)]
mod tests {
    use super::*;
    use burn::tensor::{Tensor, TensorData, Tolerance, ops::FloatElem};

    use crate::backend::TestBackend;
    type FT = FloatElem<TestBackend>;

    // Input shared by both tests — generated with np.random.seed(42), shape [1, 5, 3, 3]
    fn test_input(
        device: &<TestBackend as burn::tensor::backend::Backend>::Device,
    ) -> Tensor<TestBackend, 4> {
        Tensor::<TestBackend, 4>::from_floats(
            [[
                [
                    [0.49671414, -0.13826430, 0.64768857],
                    [1.52302980, -0.23415338, -0.23413695],
                    [1.57921280, 0.76743470, -0.46947438],
                ],
                [
                    [0.54256004, -0.46341768, -0.46572974],
                    [0.24196227, -1.91328020, -1.72491790],
                    [-0.56228750, -1.01283110, 0.31424734],
                ],
                [
                    [-0.90802410, -1.41230370, 1.46564880],
                    [-0.22577630, 0.06752820, -1.42474820],
                    [-0.54438275, 0.11092259, -1.15099360],
                ],
                [
                    [0.37569803, -0.60063870, -0.29169375],
                    [-0.60170660, 1.85227820, -0.01349723],
                    [-1.05771090, 0.82254493, -1.22084370],
                ],
                [
                    [0.20886360, -1.95967010, -1.32818600],
                    [0.19686124, 0.73846656, 0.17136829],
                    [-0.11564828, -0.30110368, -1.47852200],
                ],
            ]],
            device,
        )
    }

    #[test]
    fn lrn_with_odd_size_attr() {
        // Model: size=3, alpha=0.0001, beta=0.75, bias=1.0
        // Input/output generated by lrn.py using np.random.seed(42)
        let device = Default::default();
        let model: lrn_size3::Model<TestBackend> = lrn_size3::Model::default();

        let output = model.forward(test_input(&device));

        let expected = TensorData::from([[
            [
                [0.49670744, -0.13826350, 0.64767830],
                [1.52293920, -0.23413163, -0.23411924],
                [1.57910190, 0.76740370, -0.46947062],
            ],
            [
                [0.54256004, -0.46341768, -0.46572974],
                [0.24196227, -1.91328020, -1.72491790],
                [-0.56228750, -1.01283110, 0.31424734],
            ],
            [
                [-0.90802410, -1.41230370, 1.46564880],
                [-0.22577630, 0.06752820, -1.42474820],
                [-0.54438275, 0.11092259, -1.15099360],
            ],
            [
                [0.37569803, -0.60063870, -0.29169375],
                [-0.60170660, 1.85227820, -0.01349723],
                [-1.05771090, 0.82254493, -1.22084370],
            ],
            [
                [0.20886360, -1.95967010, -1.32818600],
                [0.19686124, 0.73846656, 0.17136829],
                [-0.11564828, -0.30110368, -1.47852200],
            ],
        ]]);

        output
            .to_data()
            .assert_approx_eq::<FT>(&expected, Tolerance::default());
    }

    #[test]
    fn lrn_with_even_size_attr() {
        // Model: size=2, alpha=0.0001, beta=0.75, bias=1.0
        // Input/output generated by lrn.py using np.random.seed(42)
        let device = Default::default();
        let model: lrn_size2::Model<TestBackend> = lrn_size2::Model::default();

        let output = model.forward(test_input(&device));

        let expected = TensorData::from([[
            [
                [0.49670407, -0.13826309, 0.64767313],
                [1.52289400, -0.23412077, -0.23411036],
                [1.57904640, 0.76738820, -0.46946877],
            ],
            [
                [0.54256004, -0.46341768, -0.46572974],
                [0.24196227, -1.91328020, -1.72491790],
                [-0.56228750, -1.01283110, 0.31424734],
            ],
            [
                [-0.90802410, -1.41230370, 1.46564880],
                [-0.22577630, 0.06752820, -1.42474820],
                [-0.54438275, 0.11092259, -1.15099360],
            ],
            [
                [0.37569803, -0.60063870, -0.29169375],
                [-0.60170660, 1.85227820, -0.01349723],
                [-1.05771090, 0.82254493, -1.22084370],
            ],
            [
                [0.20886360, -1.95967010, -1.32818600],
                [0.19686124, 0.73846656, 0.17136829],
                [-0.11564828, -0.30110368, -1.47852200],
            ],
        ]]);

        output
            .to_data()
            .assert_approx_eq::<FT>(&expected, Tolerance::default());
    }

    #[test]
    fn lrn_with_non_default_params() {
        // Model: size=3, alpha=0.01, beta=0.5, bias=2.0
        // Input/output generated by lrn.py using np.random.seed(42)
        let device = Default::default();
        let model: lrn_non_default::Model<TestBackend> = lrn_non_default::Model::default();

        let output = model.forward(test_input(&device));

        let expected = TensorData::from([[
            [
                [0.35107170, -0.09774858, 0.45774227],
                [1.07481670, -0.16506116, -0.16514334],
                [1.11406620, 0.54192954, -0.33188027],
            ],
            [
                [0.38364790, -0.32768580, -0.32932067],
                [0.17109317, -1.35289350, -1.21970120],
                [-0.39759730, -0.71617970, 0.22220643],
            ],
            [
                [-0.64207000, -0.99864954, 1.03637020],
                [-0.15964796, 0.04774965, -1.00744920],
                [-0.38493675, 0.07843412, -0.81387540],
            ],
            [
                [0.26565862, -0.42471570, -0.20625862],
                [-0.42547083, 1.30975850, -0.00954398],
                [-0.74791455, 0.58162713, -0.86326680],
            ],
            [
                [0.14768887, -1.38569600, -0.93916935],
                [0.13920192, 0.52217470, 0.12117568],
                [-0.08177569, -0.21291246, -1.04547290],
            ],
        ]]);

        output
            .to_data()
            // Slightly increase relative tolerance from 5e-3 to 6e-3 as two elements exceeded the default tolerance
            .assert_approx_eq::<FT>(&expected, Tolerance::default().set_relative(6e-3));
    }
}
