[package]
name = "burn-onnx-runner"
version = "0.1.0"
edition = "2024"

[workspace]

[dependencies]
burn = { git = "https://github.com/tracel-ai/burn", default-features = false, features = ["std", "flex"], rev = "13f0a12b71ad83c1f9edeac22dea325dcb612397" }
burn-store = { git = "https://github.com/tracel-ai/burn", default-features = false, features = ["std"], rev = "13f0a12b71ad83c1f9edeac22dea325dcb612397" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[profile.release]
opt-level = 1
debug = false
