[package]
name = "burn-onnx-runner"
version = "0.1.0"
edition = "2024"

[workspace]

[dependencies]
burn = { git = "https://github.com/tracel-ai/burn", default-features = false, features = ["std", "flex"], rev = "b8693f3b9f826d0ada194754c171b129fd78b3e4" }
burn-store = { git = "https://github.com/tracel-ai/burn", default-features = false, features = ["std"], rev = "b8693f3b9f826d0ada194754c171b129fd78b3e4" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[profile.release]
opt-level = 1
debug = false
