//! Integration tests driven entirely by `build.rs`-generated artifacts.
//!
//! The compile-time flow is:
//!
//!   1. `build.rs` reads `expectations.toml` and, for every `pass`
//!      entry, runs `ModelGen` on `vendor/node/<name>/model.onnx`.
//!   2. `build.rs` introspects each `model.onnx` to get input/output
//!      rank and dtype, and emits three generated files into
//!      `$OUT_DIR`: `models.rs`, `harness.rs`, and `manifest.rs`.
//!   3. This file `include!`s all three. `models.rs` brings every
//!      generated `Model` struct into `generated::<name>::Model`;
//!      `harness.rs` provides one `#[test] fn <name>()` per test
//!      whose introspection succeeded; `manifest.rs` provides the
//!      `HARNESS_TESTS` / `CODEGEN_ONLY_TESTS` name lists that
//!      `verify_expectations_match_tests` compares against
//!      `expectations.toml`.
//!
//! No per-test macros and no compile-time name lists live in this file
//! anymore. Adding a new upstream test is:
//!
//!   1. Drop it into `vendor/node/test_<name>/`.
//!   2. Add an entry to `expectations.toml`.
//!
//! The drift check ensures both sides stay in sync; the rest is
//! automatic.

#![allow(clippy::approx_constant)]

// Some generated model files use `alloc::vec::Vec` in runtime codegen
// (gathernd, slice with runtime tensor indices, tile with runtime
// repeats). Pull the alloc crate into scope so those paths resolve
// when the test binary links the generated modules. onnx-tests does
// the same in its own test_mod.rs.
extern crate alloc;

mod backend;

use std::path::PathBuf;

use burn::tensor::{Device, Tensor, TensorData, Tolerance};
use onnx_official_tests::expectations::{Expectations, Status};
use onnx_official_tests::pb_loader::{FloatTensor, load_float_tensor};

type FT = f32;

/// All `Model` structs generated by `burn-onnx::ModelGen`. One
/// submodule per test, produced by `build.rs`. Both harnessable tests
/// and codegen-only tests are declared here so rustc compiles every
/// generated `Model`; the codegen-only ones simply have no `#[test]`
/// function pointing at them.
#[allow(clippy::type_complexity, non_snake_case)]
pub mod generated {
    include!(concat!(env!("OUT_DIR"), "/models.rs"));
}

/// Path to a vendored test directory, relative to the crate root.
fn vendor_dir(test_name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("vendor/node")
        .join(test_name)
}

/// Path to a file inside a vendored test's `test_data_set_0/` folder.
/// Used by the `build.rs`-generated harness so each `#[test]` can be a
/// straight-line sequence of loads and comparisons.
fn vendor_file(test_name: &str, file: &str) -> PathBuf {
    vendor_dir(test_name).join("test_data_set_0").join(file)
}

// The build script emits every `#[test]` function in this file via
// `include!`. Each one calls `vendor_file()` and constructs a
// `generated::<name>::Model::<TestBackend>::new(&device)`, so these
// names must be in scope here before the include point.
//
// Upstream ONNX test names mix cases (e.g. `test_gemm_transposeA`,
// `test_nllloss_NC_expanded`); we mirror them verbatim so failures map
// 1:1 to `vendor/node/` directory names. `build.rs` emits
// `#[allow(non_snake_case)]` on each generated #[test] to silence the
// style lint without moving tests under a submodule (which would
// change `cargo test` filter paths).
include!(concat!(env!("OUT_DIR"), "/harness.rs"));

// Compile-time lists of test names that are expected to drive a
// `#[test]` function (`HARNESS_TESTS`) and pass-listed entries that
// were skipped from harness emission (`CODEGEN_ONLY_TESTS`). These are
// the manifest against which the drift check compares
// `expectations.toml`.
include!(concat!(env!("OUT_DIR"), "/manifest.rs"));

/// Verify that `expectations.toml`, the `build.rs`-generated manifest,
/// and the vendored test directories all agree. Catches the three
/// easy mistakes:
///
///   * A test exists under `vendor/node/` but has no entry in
///     `expectations.toml` — a contributor added data and forgot the
///     expectation row.
///   * `expectations.toml` has an entry with no matching vendor dir —
///     stale documentation pointing at a removed or renamed test.
///   * A row is marked `pass` but didn't produce either a harness
///     entry or a codegen-only entry — the build script's introspection
///     path has a gap.
#[test]
fn verify_expectations_match_tests() {
    let expectations_path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("expectations.toml");
    let expectations = Expectations::load(&expectations_path)
        .unwrap_or_else(|e| panic!("loading {}: {e}", expectations_path.display()));

    // Walk vendor/node/ to see what the on-disk test directories are.
    let vendor_root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("vendor/node");
    let on_disk: std::collections::BTreeSet<String> = std::fs::read_dir(&vendor_root)
        .unwrap_or_else(|e| panic!("reading {}: {e}", vendor_root.display()))
        .filter_map(|entry| {
            let entry = entry.ok()?;
            if !entry.file_type().ok()?.is_dir() {
                return None;
            }
            let name = entry.file_name().into_string().ok()?;
            if name.starts_with("test_") {
                Some(name)
            } else {
                None
            }
        })
        .collect();

    let declared: std::collections::BTreeSet<&str> =
        expectations.entries.keys().map(String::as_str).collect();

    // ---- Cross-check 1: vendor/ vs expectations.toml ----
    let on_disk_strs: std::collections::BTreeSet<&str> =
        on_disk.iter().map(String::as_str).collect();
    let only_on_disk: Vec<&&str> = on_disk_strs.difference(&declared).collect();
    let only_declared: Vec<&&str> = declared.difference(&on_disk_strs).collect();
    assert!(
        only_on_disk.is_empty() && only_declared.is_empty(),
        "vendor/node/ and expectations.toml have drifted.\n  \
         Only in vendor/node/:     {only_on_disk:?}\n  \
         Only in expectations.toml: {only_declared:?}"
    );

    // ---- Cross-check 2: every Pass row shows up in the manifest ----
    //
    // Either HARNESS_TESTS (introspection succeeded) or CODEGEN_ONLY_TESTS
    // (introspection skipped for a documented edge case). A Pass entry
    // that appears in neither means build.rs silently dropped it
    // without even a cargo warning — a latent bug.
    let harness: std::collections::BTreeSet<&str> = HARNESS_TESTS.iter().copied().collect();
    let codegen_only: std::collections::BTreeSet<&str> =
        CODEGEN_ONLY_TESTS.iter().copied().collect();
    let manifest_union: std::collections::BTreeSet<&str> =
        harness.union(&codegen_only).copied().collect();

    let declared_passes: std::collections::BTreeSet<&str> = expectations
        .entries
        .iter()
        .filter(|(_, entry)| entry.status == Status::Pass)
        .map(|(k, _)| k.as_str())
        .collect();

    let pass_not_in_manifest: Vec<&&str> = declared_passes.difference(&manifest_union).collect();
    let manifest_not_in_pass: Vec<&&str> = manifest_union.difference(&declared_passes).collect();
    assert!(
        pass_not_in_manifest.is_empty() && manifest_not_in_pass.is_empty(),
        "pass-list and build.rs manifest have drifted.\n  \
         Pass in expectations.toml but missing from manifest: {pass_not_in_manifest:?}\n  \
         In manifest but not marked Pass:                     {manifest_not_in_pass:?}"
    );

    // ---- Cross-check 3: harness and codegen-only are disjoint ----
    let intersection: Vec<_> = harness.intersection(&codegen_only).collect();
    assert!(
        intersection.is_empty(),
        "test(s) appear in both HARNESS_TESTS and CODEGEN_ONLY_TESTS: {intersection:?}"
    );

    // ---- Cross-check 4: every FailCompare row shows up in the fail-compare manifest ----
    //
    // Mirrors cross-check 2 for the drift-check manifests. A FailCompare
    // entry missing from both FAIL_COMPARE_RUNNERS and
    // FAIL_COMPARE_CODEGEN_ONLY means build.rs silently dropped it,
    // which would defeat the drift check's purpose.
    let fc_runners: std::collections::BTreeSet<&str> =
        FAIL_COMPARE_RUNNERS.iter().map(|(n, _)| *n).collect();
    let fc_codegen_only: std::collections::BTreeSet<&str> =
        FAIL_COMPARE_CODEGEN_ONLY.iter().copied().collect();
    let fc_union: std::collections::BTreeSet<&str> =
        fc_runners.union(&fc_codegen_only).copied().collect();
    let declared_fail_compare: std::collections::BTreeSet<&str> = expectations
        .entries
        .iter()
        .filter(|(_, entry)| entry.status == Status::FailCompare)
        .map(|(k, _)| k.as_str())
        .collect();
    let fc_not_in_manifest: Vec<&&str> = declared_fail_compare.difference(&fc_union).collect();
    let fc_manifest_not_in_decl: Vec<&&str> = fc_union.difference(&declared_fail_compare).collect();
    assert!(
        fc_not_in_manifest.is_empty() && fc_manifest_not_in_decl.is_empty(),
        "fail-compare list and build.rs manifest have drifted.\n  \
         FailCompare in expectations.toml but missing from manifest: {fc_not_in_manifest:?}\n  \
         In fail-compare manifest but not marked FailCompare:         {fc_manifest_not_in_decl:?}"
    );
    let fc_intersection: Vec<_> = fc_runners.intersection(&fc_codegen_only).collect();
    assert!(
        fc_intersection.is_empty(),
        "test(s) appear in both FAIL_COMPARE_RUNNERS and FAIL_COMPARE_CODEGEN_ONLY: {fc_intersection:?}"
    );
}

/// Drift check: every `status = "fail-compare"` entry must still fail
/// when run against the reference output. If a runner returns `false`
/// (comparison succeeded), the underlying bug has been fixed — usually
/// via an upstream burn rev bump — and the reviewer needs to flip the
/// row to `status = "pass"` so it joins the regular harness.
///
/// Without this check, fail-compare entries stay in limbo indefinitely:
/// the build.rs pass-list filter excludes them from the harness, so
/// they produce zero signal when upstream is fixed.
///
/// Only entries that successfully introspected end up in
/// `FAIL_COMPARE_RUNNERS`; the rest are in `FAIL_COMPARE_CODEGEN_ONLY`
/// and can't be runtime-checked here (dynamic shape, rank-0 I/O, etc.).
#[test]
fn verify_fail_compare_still_fails() {
    let now_passing = collect_now_passing(FAIL_COMPARE_RUNNERS);
    assert!(
        now_passing.is_empty(),
        "fail-compare entries that now pass; flip their status to \"pass\" in expectations.toml:\n  {now_passing:#?}"
    );
}

/// Walk a runner table and return the names whose runner reports
/// `false` (comparison now passes, i.e. the upstream fix has landed).
/// Factored out of `verify_fail_compare_still_fails` so the drift
/// polarity itself can be unit-tested — see `drift_gate_polarity`.
fn collect_now_passing<'a>(runners: &'a [(&'a str, fn() -> bool)]) -> Vec<&'a str> {
    runners
        .iter()
        .filter_map(|(name, runner)| if !runner() { Some(*name) } else { None })
        .collect()
}

/// Drift-gate self-test: `collect_now_passing` must identify runners
/// that report `false` and ignore those that report `true`. Without
/// this check, a future refactor that inverts the boolean (e.g.,
/// swapping the `result.is_err()` in the generated FailCompare body)
/// would silently green the gate forever. Mirrors
/// `negative_gate_actually_gates` for the comparison machinery.
#[test]
fn drift_gate_polarity() {
    fn still_failing() -> bool {
        true
    }
    fn now_passing() -> bool {
        false
    }
    let table: &[(&str, fn() -> bool)] = &[
        ("still_failing_entry", still_failing),
        ("now_passing_entry", now_passing),
    ];
    let flagged = collect_now_passing(table);
    assert_eq!(
        flagged,
        vec!["now_passing_entry"],
        "drift gate should flag only the runner that returns false"
    );
}

/// Negative gate: prove that the comparison path inside a harness
/// test actually fails when given wrong data. Without this, a bug in
/// `assert_approx_eq` (or `load_tensor`) could silently turn the
/// whole suite into a no-op gate while every other test stayed green.
///
/// We deliberately pin this to `test_abs` rather than parameterising
/// over every generated test: the point is to verify the comparison
/// machinery is load-bearing, and `test_abs` is the simplest case
/// (FLOAT rank-3, single input, single output, no runtime inputs
/// beyond the tensor itself).
#[test]
fn negative_gate_actually_gates() {
    let device: Device = Default::default();
    let model = generated::test_abs::Model::new(&device);
    let input_ref =
        load_float_tensor(&vendor_file("test_abs", "input_0.pb")).expect("load test_abs input_0");
    let input = Tensor::<3>::from_data(TensorData::new(input_ref.values, input_ref.shape), &device);
    let output = model.forward(input);

    // Construct a deliberately wrong "expected" by adding 1.0 to every
    // element of the real reference.
    let FloatTensor { shape, values } =
        load_float_tensor(&vendor_file("test_abs", "output_0.pb")).expect("load test_abs output_0");
    let perturbed: Vec<f32> = values.iter().map(|v| v + 1.0).collect();
    let wrong = TensorData::new(perturbed, shape);

    let result = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        output
            .to_data()
            .assert_approx_eq::<FT>(&wrong, Tolerance::default());
    }));
    assert!(
        result.is_err(),
        "comparison against deliberately-perturbed reference passed; \
         the gate is not actually gating",
    );
}
