//! Opset 8 compliance tests.
//!
//! Auto-generated by gen_rust_tests.py. Edit the generator, not this file.

use super::helpers::*;
use rstest::*;

#[fixture]
#[once]
fn graph() -> OnnxGraph {
    load_model("opset_08.onnx")
}

#[rstest]
fn expand(graph: &OnnxGraph) {
    let node = find_node(graph, "expand");
    insta::assert_snapshot!(format!("{node}"), @r#"
    Expand "expand1"
      Inputs:
        expand_input: F32[1, 3]
        _: I64[2] [static(0)]
      Outputs:
        expand1_out1: F32[2, 3]
      Config:
        Static(
            [
                2,
                3,
            ],
        )
    "#);
}

#[rstest]
fn max(graph: &OnnxGraph) {
    let node = find_node(graph, "max");
    insta::assert_snapshot!(format!("{node}"), @r#"
    Max "max1"
      Inputs:
        max_a: F32[2, 3, 4]
        max_b: F32[2, 3, 4]
      Outputs:
        max1_out1: F32[2, 3, 4]
    "#);
}

#[rstest]
fn max_pool(graph: &OnnxGraph) {
    let node = find_node(graph, "maxpool2d");
    insta::assert_snapshot!(format!("{node}"), @r#"
    MaxPool2d "maxpool2d1"
      Inputs:
        maxpool_input: F32[1, 3, 8, 8]
      Outputs:
        maxpool2d1_out1: F32[1, 3, 8, 8]
      Config:
        MaxPool2dConfig {
            kernel_size: [
                2,
                2,
            ],
            strides: [
                2,
                2,
            ],
            padding: Valid,
            dilation: [
                1,
                1,
            ],
            ceil_mode: false,
            auto_pad: NotSet,
        }
    "#);
}

#[rstest]
fn mean(graph: &OnnxGraph) {
    let node = find_node(graph, "mean");
    insta::assert_snapshot!(format!("{node}"), @r#"
    Mean "mean1"
      Inputs:
        mean_a: F32[2, 3, 4]
        mean_b: F32[2, 3, 4]
      Outputs:
        mean1_out1: F32[2, 3, 4]
    "#);
}

#[rstest]
fn min(graph: &OnnxGraph) {
    let node = find_node(graph, "min");
    insta::assert_snapshot!(format!("{node}"), @r#"
    Min "min1"
      Inputs:
        min_a: F32[2, 3, 4]
        min_b: F32[2, 3, 4]
      Outputs:
        min1_out1: F32[2, 3, 4]
    "#);
}

#[rstest]
fn sum(graph: &OnnxGraph) {
    let node = find_node(graph, "sum");
    insta::assert_snapshot!(format!("{node}"), @r#"
    Sum "sum1"
      Inputs:
        sum_a: F32[2, 3, 4]
        sum_b: F32[2, 3, 4]
      Outputs:
        sum1_out1: F32[2, 3, 4]
    "#);
}

