//! Opset 2 compliance tests.
//!
//! Auto-generated by gen_rust_tests.py. Edit the generator, not this file.

use super::helpers::*;
use rstest::*;

#[fixture]
#[once]
fn graph() -> OnnxGraph {
    load_model("opset_02.onnx")
}

#[rstest]
fn pad(graph: &OnnxGraph) {
    let node = find_node(graph, "pad");
    insta::assert_snapshot!(format!("{node}"), @r#"
    Pad "pad1"
      Inputs:
        pad_input: F32[2, 3]
      Outputs:
        pad1_out1: F32[2, 3]
      Config:
        PadConfig {
            pads: Static(
                [
                    1,
                    1,
                    0,
                    0,
                ],
            ),
            constant_value: Static(
                0.0,
            ),
            mode: Constant,
        }
    "#);
}

/// Ops that require min_opset > 2: Split
#[test]
fn unsupported_ops_fail() {
    let result = load_model_result("opset_02_unsupported.onnx");
    assert!(result.is_err(), "expected parse failure for unsupported ops at opset 2");
}

