//! Opset 17 compliance tests.
//!
//! Auto-generated by gen_rust_tests.py. Edit the generator, not this file.

use super::helpers::*;
use rstest::*;

#[fixture]
#[once]
fn graph() -> OnnxGraph {
    load_model("opset_17.onnx")
}

#[rstest]
fn layer_normalization(graph: &OnnxGraph) {
    let node = find_node(graph, "layernormalization");
    insta::assert_snapshot!(format!("{node}"), @r#"
    LayerNormalization "layernormalization1"
      Inputs:
        layernormalization_input: F32[2, 3, 4]
        _: F32[4] [static(0)]
        _: F32[4] [static(1)]
      Outputs:
        layernormalization1_out1: F32[2, 3, 4]
      Config:
        LayerNormConfig {
            epsilon: 9.999999747378752e-6,
            full_precision: true,
        }
    "#);
}

