//! Opset 4 compliance tests.
//!
//! Auto-generated by gen_rust_tests.py. Edit the generator, not this file.

use super::helpers::*;

#[test]
fn concat() {
    let graph = load_model("opset_04.onnx");
    let node = find_node(&graph, "concat");
    insta::assert_snapshot!(format!("{node}"), @r#"
    Concat "concat1"
      Inputs:
        concat_a: F32[2, 3]
        concat_b: F32[2, 3]
      Outputs:
        concat1_out1: F32[?, ?]
      Config:
        ConcatConfig {
            axis: 0,
        }
    "#);
}

