//! Opset 16 compliance tests.
//!
//! Auto-generated by gen_rust_tests.py. Edit the generator, not this file.

use super::helpers::*;
use rstest::*;

#[fixture]
#[once]
fn graph() -> OnnxGraph {
    load_model("opset_16.onnx")
}

#[rstest]
fn greater_or_equal(graph: &OnnxGraph) {
    let node = find_node(graph, "greaterorequal");
    insta::assert_snapshot!(format!("{node}"), @r#"
    GreaterOrEqual "greaterorequal1"
      Inputs:
        greaterorequal_a: F32[2, 3, 4]
        greaterorequal_b: F32[2, 3, 4]
      Outputs:
        greaterorequal1_out1: Bool[2, 3, 4]
    "#);
}

#[rstest]
fn grid_sample(graph: &OnnxGraph) {
    let node = find_node(graph, "gridsample");
    insta::assert_snapshot!(format!("{node}"), @r#"
    GridSample "gridsample1"
      Inputs:
        gridsample_input: F32[1, 1, 3, 3]
        gridsample_grid: F32[1, 2, 2, 2]
      Outputs:
        gridsample1_out1: F32[?, ?, ?, ?]
      Config:
        GridSampleConfig {
            mode: Bilinear,
            padding_mode: Zeros,
            align_corners: false,
        }
    "#);
}

/// Identity is eliminated during post-processing (no-op).
/// Verify the model parses without error.
#[test]
fn identity() {
    let _graph = load_model("opset_16.onnx");
}

#[rstest]
fn if_op(graph: &OnnxGraph) {
    let node = find_node(graph, "if");
    insta::assert_snapshot!(format!("{node}"), @r#"
    If "if1"
      Inputs:
        if_condition: ScalarNative(Bool)
      Outputs:
        if1_out1: F32[2, 3]
      Config:
        IfConfig {
            then_branch: OnnxGraph {
                nodes: [
                    Constant(
                        ConstantNode {
                            name: "constant7",
                            inputs: [
                                Argument {
                                    name: "",
                                    ty: Tensor(
                                        TensorType {
                                            dtype: F32,
                                            rank: 2,
                                            static_shape: Some(
                                                [
                                                    Some(
                                                        2,
                                                    ),
                                                    Some(
                                                        3,
                                                    ),
                                                ],
                                            ),
                                        },
                                    ),
                                    value_source: Static(
                                        0,
                                    ),
                                },
                            ],
                            outputs: [
                                Argument {
                                    name: "constant7_out1",
                                    ty: Tensor(
                                        TensorType {
                                            dtype: F32,
                                            rank: 2,
                                            static_shape: Some(
                                                [
                                                    Some(
                                                        2,
                                                    ),
                                                    Some(
                                                        3,
                                                    ),
                                                ],
                                            ),
                                        },
                                    ),
                                    value_source: Constant,
                                },
                            ],
                        },
                    ),
                ],
                inputs: [],
                outputs: [
                    Argument {
                        name: "constant7_out1",
                        ty: Tensor(
                            TensorType {
                                dtype: F32,
                                rank: 2,
                                static_shape: Some(
                                    [
                                        Some(
                                            2,
                                        ),
                                        Some(
                                            3,
                                        ),
                                    ],
                                ),
                            },
                        ),
                        value_source: Constant,
                    },
                ],
                value_store: Some(
                    ValueStore {
                        tensor_store: TensorStore {
                            data: {
                                0: TensorDataRef {
                                    shape: [
                                        2,
                                        3,
                                    ],
                                    dtype: F32,
                                    source: Embedded(
                                        b"\0\0\x80?\0\0\x80?\0\0\x80?\0\0\x80?\0\0\x80?\0\0\x80?",
                                    ),
                                },
                            },
                            next_id: 1,
                        },
                        constant_map: {
                            "constant7_out1": 0,
                        },
                    },
                ),
            },
            else_branch: OnnxGraph {
                nodes: [
                    Constant(
                        ConstantNode {
                            name: "constant8",
                            inputs: [
                                Argument {
                                    name: "",
                                    ty: Tensor(
                                        TensorType {
                                            dtype: F32,
                                            rank: 2,
                                            static_shape: Some(
                                                [
                                                    Some(
                                                        2,
                                                    ),
                                                    Some(
                                                        3,
                                                    ),
                                                ],
                                            ),
                                        },
                                    ),
                                    value_source: Static(
                                        0,
                                    ),
                                },
                            ],
                            outputs: [
                                Argument {
                                    name: "constant8_out1",
                                    ty: Tensor(
                                        TensorType {
                                            dtype: F32,
                                            rank: 2,
                                            static_shape: Some(
                                                [
                                                    Some(
                                                        2,
                                                    ),
                                                    Some(
                                                        3,
                                                    ),
                                                ],
                                            ),
                                        },
                                    ),
                                    value_source: Constant,
                                },
                            ],
                        },
                    ),
                ],
                inputs: [],
                outputs: [
                    Argument {
                        name: "constant8_out1",
                        ty: Tensor(
                            TensorType {
                                dtype: F32,
                                rank: 2,
                                static_shape: Some(
                                    [
                                        Some(
                                            2,
                                        ),
                                        Some(
                                            3,
                                        ),
                                    ],
                                ),
                            },
                        ),
                        value_source: Constant,
                    },
                ],
                value_store: Some(
                    ValueStore {
                        tensor_store: TensorStore {
                            data: {
                                0: TensorDataRef {
                                    shape: [
                                        2,
                                        3,
                                    ],
                                    dtype: F32,
                                    source: Embedded(
                                        b"\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0",
                                    ),
                                },
                            },
                            next_id: 1,
                        },
                        constant_map: {
                            "constant8_out1": 0,
                        },
                    },
                ),
            },
            scope_ref_names: [],
        }
    "#);
}

#[rstest]
fn leaky_relu(graph: &OnnxGraph) {
    let node = find_node(graph, "leakyrelu");
    insta::assert_snapshot!(format!("{node}"), @r#"
    LeakyRelu "leakyrelu1"
      Inputs:
        leakyrelu_input: F32[2, 3, 4]
      Outputs:
        leakyrelu1_out1: F32[2, 3, 4]
      Config:
        LeakyReluConfig {
            alpha: 0.009999999776482582,
        }
    "#);
}

#[rstest]
fn less_or_equal(graph: &OnnxGraph) {
    let node = find_node(graph, "lessorequal");
    insta::assert_snapshot!(format!("{node}"), @r#"
    LessOrEqual "lessorequal1"
      Inputs:
        lessorequal_a: F32[2, 3, 4]
        lessorequal_b: F32[2, 3, 4]
      Outputs:
        lessorequal1_out1: Bool[2, 3, 4]
    "#);
}

#[rstest]
fn p_relu(graph: &OnnxGraph) {
    let node = find_node(graph, "prelu");
    insta::assert_snapshot!(format!("{node}"), @r#"
    PRelu "prelu1"
      Inputs:
        prelu_input: F32[2, 3, 4]
        _: F32[1] [static(0)]
      Outputs:
        prelu1_out1: F32[2, 3, 4]
    "#);
}

#[rstest]
fn scatter_elements(graph: &OnnxGraph) {
    let node = find_node(graph, "scatterelements");
    insta::assert_snapshot!(format!("{node}"), @r#"
    ScatterElements "scatterelements1"
      Inputs:
        scatterelements_input: F32[3, 3]
        constant2_out1: I64[1, 3] [constant]
        scatterelements_updates: F32[1, 3]
      Outputs:
        scatterelements1_out1: F32[3, 3]
      Config:
        ScatterElementsConfig {
            axis: 0,
            reduction: None,
        }
    "#);
}

#[rstest]
fn scatter_nd(graph: &OnnxGraph) {
    let node = find_node(graph, "scatternd");
    insta::assert_snapshot!(format!("{node}"), @r#"
    ScatterND "scatternd1"
      Inputs:
        scatternd_input: F32[4, 4]
        constant3_out1: I64[2, 1] [constant]
        scatternd_updates: F32[2, 4]
      Outputs:
        scatternd1_out1: F32[4, 4]
      Config:
        ScatterNDConfig {
            reduction: None,
        }
    "#);
}

#[rstest]
fn where_op(graph: &OnnxGraph) {
    let node = find_node(graph, "where");
    insta::assert_snapshot!(format!("{node}"), @r#"
    Where "where1"
      Inputs:
        where_condition: Bool[2, 3]
        where_x: F32[2, 3]
        where_y: F32[2, 3]
      Outputs:
        where1_out1: F32[2, 3]
    "#);
}
