//! Opset 7 compliance tests.
//!
//! Auto-generated by gen_rust_tests.py. Edit the generator, not this file.

use super::helpers::*;
use rstest::*;

#[fixture]
#[once]
fn graph() -> OnnxGraph {
    load_model("opset_07.onnx")
}

#[rstest]
fn acos(graph: &OnnxGraph) {
    let node = find_node(graph, "acos");
    insta::assert_snapshot!(format!("{node}"), @r#"
    Acos "acos1"
      Inputs:
        acos_input: F32[2, 3, 4]
      Outputs:
        acos1_out1: F32[2, 3, 4]
    "#);
}

#[rstest]
fn add(graph: &OnnxGraph) {
    let node = find_node(graph, "add");
    insta::assert_snapshot!(format!("{node}"), @r#"
    Add "add1"
      Inputs:
        add_a: F32[2, 3, 4]
        add_b: F32[2, 3, 4]
      Outputs:
        add1_out1: F32[2, 3, 4]
    "#);
}

#[rstest]
fn and_op(graph: &OnnxGraph) {
    let node = find_node(graph, "and");
    insta::assert_snapshot!(format!("{node}"), @r#"
    And "and1"
      Inputs:
        and_a: Bool[2, 3, 4]
        and_b: Bool[2, 3, 4]
      Outputs:
        and1_out1: Bool[2, 3, 4]
    "#);
}

#[rstest]
fn asin(graph: &OnnxGraph) {
    let node = find_node(graph, "asin");
    insta::assert_snapshot!(format!("{node}"), @r#"
    Asin "asin1"
      Inputs:
        asin_input: F32[2, 3, 4]
      Outputs:
        asin1_out1: F32[2, 3, 4]
    "#);
}

#[rstest]
fn atan(graph: &OnnxGraph) {
    let node = find_node(graph, "atan");
    insta::assert_snapshot!(format!("{node}"), @r#"
    Atan "atan1"
      Inputs:
        atan_input: F32[2, 3, 4]
      Outputs:
        atan1_out1: F32[2, 3, 4]
    "#);
}

#[rstest]
fn average_pool(graph: &OnnxGraph) {
    let node = find_node(graph, "averagepool2d");
    insta::assert_snapshot!(format!("{node}"), @r#"
    AveragePool2d "averagepool2d1"
      Inputs:
        averagepool_input: F32[1, 3, 8, 8]
      Outputs:
        averagepool2d1_out1: F32[?, ?, ?, ?]
      Config:
        AvgPool2dConfig {
            kernel_size: [
                2,
                2,
            ],
            strides: [
                2,
                2,
            ],
            padding: Valid,
            count_include_pad: false,
            dilation: [
                1,
                1,
            ],
            ceil_mode: false,
            auto_pad: NotSet,
        }
    "#);
}

#[rstest]
fn batch_normalization(graph: &OnnxGraph) {
    let node = find_node(graph, "batchnormalization");
    insta::assert_snapshot!(format!("{node}"), @r#"
    BatchNormalization "batchnormalization1"
      Inputs:
        batchnormalization_input: F32[1, 3, 4, 4]
        _: F32[3] [static(0)]
        _: F32[3] [static(1)]
        _: F32[3] [static(2)]
        _: F32[3] [static(3)]
      Outputs:
        batchnormalization1_out1: F32[1, 3, 4, 4]
        batchnormalization1_out2: ScalarNative(F32)
        batchnormalization1_out3: ScalarNative(F32)
        batchnormalization1_out4: ScalarNative(F32)
        batchnormalization1_out5: ScalarNative(F32)
      Config:
        Static(
            BatchNormStaticConfig {
                epsilon: 0.0,
                momentum: 0.0,
            },
        )
    "#);
}

#[rstest]
fn cos(graph: &OnnxGraph) {
    let node = find_node(graph, "cos");
    insta::assert_snapshot!(format!("{node}"), @r#"
    Cos "cos1"
      Inputs:
        cos_input: F32[2, 3, 4]
      Outputs:
        cos1_out1: F32[2, 3, 4]
    "#);
}

#[rstest]
fn div(graph: &OnnxGraph) {
    let node = find_node(graph, "div");
    insta::assert_snapshot!(format!("{node}"), @r#"
    Div "div1"
      Inputs:
        div_a: F32[2, 3, 4]
        div_b: F32[2, 3, 4]
      Outputs:
        div1_out1: F32[2, 3, 4]
    "#);
}

/// Dropout is eliminated during post-processing (no-op).
/// Verify the model parses without error.
#[test]
fn dropout() {
    let _graph = load_model("opset_07.onnx");
}

#[rstest]
fn equal(graph: &OnnxGraph) {
    let node = find_node(graph, "equal");
    insta::assert_snapshot!(format!("{node}"), @r#"
    Equal "equal1"
      Inputs:
        equal_a: F32[2, 3, 4]
        equal_b: F32[2, 3, 4]
      Outputs:
        equal1_out1: Bool[2, 3, 4]
    "#);
}

#[rstest]
fn gru(graph: &OnnxGraph) {
    let node = find_node(graph, "gru");
    insta::assert_snapshot!(format!("{node}"), @r#"
    Gru "gru1"
      Inputs:
        gru_input: F32[1, 2, 3]
        _: F32[1, 12, 3] [static(4)]
        _: F32[1, 12, 4] [static(5)]
      Outputs:
        gru1_out1: F32[?, ?, ?, ?]
      Config:
        GruConfig {
            input_size: 3,
            hidden_size: 4,
            direction: Forward,
            has_bias: false,
            has_initial_h: false,
            batch_first: false,
            clip: None,
            linear_before_reset: false,
            gate_activation: Sigmoid,
            hidden_activation: Tanh,
            activation_alpha: None,
            activation_beta: None,
        }
    "#);
}

#[rstest]
fn gemm(graph: &OnnxGraph) {
    let node = find_node(graph, "gemm");
    insta::assert_snapshot!(format!("{node}"), @r#"
    Gemm "gemm1"
      Inputs:
        gemm_a: F32[2, 3]
        constant7_out1: F32[3, 4] [constant]
        constant8_out1: F32[4] [constant]
      Outputs:
        gemm1_out1: F32[?, ?]
      Config:
        GemmConfig {
            alpha: 1.0,
            beta: 1.0,
            trans_a: 0,
            trans_b: 0,
        }
    "#);
}

#[rstest]
fn greater(graph: &OnnxGraph) {
    let node = find_node(graph, "greater");
    insta::assert_snapshot!(format!("{node}"), @r#"
    Greater "greater1"
      Inputs:
        greater_a: F32[2, 3, 4]
        greater_b: F32[2, 3, 4]
      Outputs:
        greater1_out1: Bool[2, 3, 4]
    "#);
}

#[rstest]
fn lstm(graph: &OnnxGraph) {
    let node = find_node(graph, "lstm");
    insta::assert_snapshot!(format!("{node}"), @r#"
    Lstm "lstm1"
      Inputs:
        lstm_input: F32[1, 2, 3]
        _: F32[1, 16, 3] [static(8)]
        _: F32[1, 16, 4] [static(9)]
      Outputs:
        lstm1_out1: F32[?, ?, ?, ?]
      Config:
        LstmConfig {
            input_size: 3,
            hidden_size: 4,
            direction: Forward,
            has_bias: false,
            has_initial_h: false,
            has_initial_c: false,
            has_peephole: false,
            batch_first: false,
            clip: None,
            input_forget: false,
            gate_activation: Sigmoid,
            cell_activation: Tanh,
            hidden_activation: Tanh,
        }
    "#);
}

#[rstest]
fn less(graph: &OnnxGraph) {
    let node = find_node(graph, "less");
    insta::assert_snapshot!(format!("{node}"), @r#"
    Less "less1"
      Inputs:
        less_a: F32[2, 3, 4]
        less_b: F32[2, 3, 4]
      Outputs:
        less1_out1: Bool[2, 3, 4]
    "#);
}

#[rstest]
fn mul(graph: &OnnxGraph) {
    let node = find_node(graph, "mul");
    insta::assert_snapshot!(format!("{node}"), @r#"
    Mul "mul1"
      Inputs:
        mul_a: F32[2, 3, 4]
        mul_b: F32[2, 3, 4]
      Outputs:
        mul1_out1: F32[2, 3, 4]
    "#);
}

#[rstest]
fn or_op(graph: &OnnxGraph) {
    let node = find_node(graph, "or");
    insta::assert_snapshot!(format!("{node}"), @r#"
    Or "or1"
      Inputs:
        or_a: Bool[2, 3, 4]
        or_b: Bool[2, 3, 4]
      Outputs:
        or1_out1: Bool[2, 3, 4]
    "#);
}

#[rstest]
fn p_relu(graph: &OnnxGraph) {
    let node = find_node(graph, "prelu");
    insta::assert_snapshot!(format!("{node}"), @r#"
    PRelu "prelu1"
      Inputs:
        prelu_input: F32[2, 3, 4]
        _: F32[1] [static(10)]
      Outputs:
        prelu1_out1: F32[2, 3, 4]
    "#);
}

#[rstest]
fn pow(graph: &OnnxGraph) {
    let node = find_node(graph, "pow");
    insta::assert_snapshot!(format!("{node}"), @r#"
    Pow "pow1"
      Inputs:
        pow_a: F32[2, 3, 4]
        pow_b: F32[2, 3, 4]
      Outputs:
        pow1_out1: F32[2, 3, 4]
    "#);
}

#[rstest]
fn sin(graph: &OnnxGraph) {
    let node = find_node(graph, "sin");
    insta::assert_snapshot!(format!("{node}"), @r#"
    Sin "sin1"
      Inputs:
        sin_input: F32[2, 3, 4]
      Outputs:
        sin1_out1: F32[2, 3, 4]
    "#);
}

#[rstest]
fn sub(graph: &OnnxGraph) {
    let node = find_node(graph, "sub");
    insta::assert_snapshot!(format!("{node}"), @r#"
    Sub "sub1"
      Inputs:
        sub_a: F32[2, 3, 4]
        sub_b: F32[2, 3, 4]
      Outputs:
        sub1_out1: F32[2, 3, 4]
    "#);
}

#[rstest]
fn tan(graph: &OnnxGraph) {
    let node = find_node(graph, "tan");
    insta::assert_snapshot!(format!("{node}"), @r#"
    Tan "tan1"
      Inputs:
        tan_input: F32[2, 3, 4]
      Outputs:
        tan1_out1: F32[2, 3, 4]
    "#);
}

#[rstest]
fn xor_op(graph: &OnnxGraph) {
    let node = find_node(graph, "xor");
    insta::assert_snapshot!(format!("{node}"), @r#"
    Xor "xor1"
      Inputs:
        xor_a: Bool[2, 3, 4]
        xor_b: Bool[2, 3, 4]
      Outputs:
        xor1_out1: Bool[2, 3, 4]
    "#);
}
