//! Opset 2 compliance tests.
//!
//! Auto-generated by gen_rust_tests.py. Edit the generator, not this file.

use super::helpers::*;
use rstest::*;

#[fixture]
#[once]
fn graph() -> OnnxGraph {
    load_model("opset_02.onnx")
}

#[rstest]
fn global_lp_pool(graph: &OnnxGraph) {
    let node = find_node(graph, "globallppool");
    insta::assert_snapshot!(format!("{node}"), @r#"
    GlobalLpPool "globallppool1"
      Inputs:
        globallppool_input: F32[1, 3, 8, 8]
      Outputs:
        globallppool1_out1: F32[1, 3, 1, 1]
      Config:
        GlobalLpPoolConfig {
            p: 2.0,
        }
    "#);
}

#[rstest]
fn lp_pool(graph: &OnnxGraph) {
    let node = find_node(graph, "lppool2d");
    insta::assert_snapshot!(format!("{node}"), @r#"
    LpPool2d "lppool2d1"
      Inputs:
        lppool_input: F32[1, 3, 8, 8]
      Outputs:
        lppool2d1_out1: F32[1, 3, 8, 8]
      Config:
        LpPool2dConfig {
            kernel_size: [
                2,
                2,
            ],
            strides: [
                2,
                2,
            ],
            padding: Valid,
            dilation: [
                1,
                1,
            ],
            ceil_mode: false,
            auto_pad: NotSet,
            p: 2.0,
        }
    "#);
}

#[rstest]
fn pad(graph: &OnnxGraph) {
    let node = find_node(graph, "pad");
    insta::assert_snapshot!(format!("{node}"), @r#"
    Pad "pad1"
      Inputs:
        pad_input: F32[2, 3]
      Outputs:
        pad1_out1: F32[2, 3]
      Config:
        PadConfig {
            pads: Static(
                [
                    (
                        0,
                        0,
                    ),
                    (
                        1,
                        1,
                    ),
                ],
            ),
            constant_value: Static(
                0.0,
            ),
            mode: Constant,
        }
    "#);
}

#[rstest]
fn split(graph: &OnnxGraph) {
    let node = find_node(graph, "split");
    insta::assert_snapshot!(format!("{node}"), @r#"
    Split "split1"
      Inputs:
        split_input: F32[2, 6]
      Outputs:
        split1_out1: F32[2, 3]
        split1_out2: F32[2, 3]
      Config:
        SplitConfig {
            axis: 1,
            split_size: None,
            split_sizes: Some(
                Static(
                    [
                        3,
                        3,
                    ],
                ),
            ),
            num_outputs: None,
        }
    "#);
}
