//! Opset 12 compliance tests.
//!
//! Auto-generated by gen_rust_tests.py. Edit the generator, not this file.

use super::helpers::*;
use rstest::*;

#[fixture]
#[once]
fn graph() -> OnnxGraph {
    load_model("opset_12.onnx")
}

#[rstest]
fn arg_max(graph: &OnnxGraph) {
    let node = find_node(graph, "argmax");
    insta::assert_snapshot!(format!("{node}"), @r#"
    ArgMax "argmax1"
      Inputs:
        argmax_input: F32[2, 3, 4]
      Outputs:
        argmax1_out1: I64[?, ?, ?]
      Config:
        ArgMaxConfig {
            axis: 1,
            keepdims: true,
        }
    "#);
}

#[rstest]
fn arg_min(graph: &OnnxGraph) {
    let node = find_node(graph, "argmin");
    insta::assert_snapshot!(format!("{node}"), @r#"
    ArgMin "argmin1"
      Inputs:
        argmin_input: F32[2, 3, 4]
      Outputs:
        argmin1_out1: I64[?, ?, ?]
      Config:
        ArgMinConfig {
            axis: 1,
            keepdims: true,
        }
    "#);
}

#[rstest]
fn celu(graph: &OnnxGraph) {
    let node = find_node(graph, "celu");
    insta::assert_snapshot!(format!("{node}"), @r#"
    Celu "celu1"
      Inputs:
        celu_input: F32[2, 3, 4]
      Outputs:
        celu1_out1: F32[2, 3, 4]
      Config:
        CeluConfig {
            alpha: 1.0,
        }
    "#);
}

#[rstest]
fn clip(graph: &OnnxGraph) {
    let node = find_node(graph, "clip");
    insta::assert_snapshot!(format!("{node}"), @r#"
    Clip "clip1"
      Inputs:
        clip_input: F32[2, 3, 4]
        _: Scalar(F32) [static(0)]
        _: Scalar(F32) [static(1)]
      Outputs:
        clip1_out1: F32[2, 3, 4]
      Config:
        ClipConfig {
            min: Some(
                Static(
                    0.0,
                ),
            ),
            max: Some(
                Static(
                    6.0,
                ),
            ),
        }
    "#);
}

#[rstest]
fn constant(graph: &OnnxGraph) {
    let node = find_node(graph, "constant");
    insta::assert_snapshot!(format!("{node}"), @r#"
    Constant "constant5"
      Inputs:
        _: I64[2, 2] [static(4)]
      Outputs:
        constant5_out1: I64[2, 2] [constant]
    "#);
}

/// Dropout is eliminated during post-processing (no-op).
/// Verify the model parses without error.
#[test]
fn dropout() {
    let _graph = load_model("opset_12.onnx");
}

#[rstest]
fn gather_nd(graph: &OnnxGraph) {
    let node = find_node(graph, "gathernd");
    insta::assert_snapshot!(format!("{node}"), @r#"
    GatherND "gathernd1"
      Inputs:
        gathernd_input: F32[2, 3, 4]
        constant5_out1: I64[2, 2] [constant]
      Outputs:
        gathernd1_out1: F32[?, ?]
      Config:
        GatherNDConfig {
            batch_dims: 0,
        }
    "#);
}

#[rstest]
fn greater_or_equal(graph: &OnnxGraph) {
    let node = find_node(graph, "greaterorequal");
    insta::assert_snapshot!(format!("{node}"), @r#"
    GreaterOrEqual "greaterorequal1"
      Inputs:
        greaterorequal_a: F32[2, 3, 4]
        greaterorequal_b: F32[2, 3, 4]
      Outputs:
        greaterorequal1_out1: Bool[?, ?, ?]
    "#);
}

#[rstest]
fn less_or_equal(graph: &OnnxGraph) {
    let node = find_node(graph, "lessorequal");
    insta::assert_snapshot!(format!("{node}"), @r#"
    LessOrEqual "lessorequal1"
      Inputs:
        lessorequal_a: F32[2, 3, 4]
        lessorequal_b: F32[2, 3, 4]
      Outputs:
        lessorequal1_out1: Bool[?, ?, ?]
    "#);
}

#[rstest]
fn max(graph: &OnnxGraph) {
    let node = find_node(graph, "max");
    insta::assert_snapshot!(format!("{node}"), @r#"
    Max "max1"
      Inputs:
        max_a: F32[2, 3, 4]
        max_b: F32[2, 3, 4]
      Outputs:
        max1_out1: F32[2, 3, 4]
    "#);
}

#[rstest]
fn max_pool(graph: &OnnxGraph) {
    let node = find_node(graph, "maxpool2d");
    insta::assert_snapshot!(format!("{node}"), @r#"
    MaxPool2d "maxpool2d1"
      Inputs:
        maxpool_input: F32[1, 3, 8, 8]
      Outputs:
        maxpool2d1_out1: F32[1, 3, 8, 8]
      Config:
        MaxPool2dConfig {
            kernel_size: [
                2,
                2,
            ],
            strides: [
                2,
                2,
            ],
            padding: Valid,
            dilation: [
                1,
                1,
            ],
            ceil_mode: false,
            auto_pad: NotSet,
        }
    "#);
}

#[rstest]
fn min(graph: &OnnxGraph) {
    let node = find_node(graph, "min");
    insta::assert_snapshot!(format!("{node}"), @r#"
    Min "min1"
      Inputs:
        min_a: F32[2, 3, 4]
        min_b: F32[2, 3, 4]
      Outputs:
        min1_out1: F32[2, 3, 4]
    "#);
}

#[rstest]
fn pow(graph: &OnnxGraph) {
    let node = find_node(graph, "pow");
    insta::assert_snapshot!(format!("{node}"), @r#"
    Pow "pow1"
      Inputs:
        pow_a: F32[2, 3, 4]
        pow_b: F32[2, 3, 4]
      Outputs:
        pow1_out1: F32[2, 3, 4]
    "#);
}

#[rstest]
fn reduce_max(graph: &OnnxGraph) {
    let node = find_node(graph, "reducemax");
    insta::assert_snapshot!(format!("{node}"), @r#"
    ReduceMax "reducemax1"
      Inputs:
        reducemax_input: F32[2, 3, 4]
      Outputs:
        reducemax1_out1: F32[2, 1, 4]
      Config:
        ReduceConfig {
            dims: [
                1,
            ],
            keepdims: true,
        }
    "#);
}

#[rstest]
fn reduce_min(graph: &OnnxGraph) {
    let node = find_node(graph, "reducemin");
    insta::assert_snapshot!(format!("{node}"), @r#"
    ReduceMin "reducemin1"
      Inputs:
        reducemin_input: F32[2, 3, 4]
      Outputs:
        reducemin1_out1: F32[2, 1, 4]
      Config:
        ReduceConfig {
            dims: [
                1,
            ],
            keepdims: true,
        }
    "#);
}

