//! Opset 20 compliance tests.
//!
//! Auto-generated by gen_rust_tests.py. Edit the generator, not this file.

use super::helpers::*;
use rstest::*;

#[fixture]
#[once]
fn graph() -> OnnxGraph {
    load_model("opset_20.onnx")
}

#[rstest]
fn constant_of_shape(graph: &OnnxGraph) {
    let node = find_node(graph, "constantofshape");
    insta::assert_snapshot!(format!("{node}"), @r#"
    ConstantOfShape "constantofshape1"
      Inputs:
        _: Shape(2) [static(0)]
      Outputs:
        constantofshape1_out1: F32[?, ?]
      Config:
        ConstantOfShapeConfig {
            shape: Static(
                [
                    2,
                    3,
                ],
            ),
            value: Some(
                TensorData {
                    bytes: Bytes {
                        data: [
                            0,
                            0,
                            128,
                            "...",
                        ],
                        len: 4,
                    },
                    shape: [
                        1,
                    ],
                    dtype: F32,
                },
            ),
        }
    "#);
}

#[rstest]
fn gelu(graph: &OnnxGraph) {
    let node = find_node(graph, "gelu");
    insta::assert_snapshot!(format!("{node}"), @r#"
    Gelu "gelu1"
      Inputs:
        gelu_input: F32[2, 3, 4]
      Outputs:
        gelu1_out1: F32[2, 3, 4]
    "#);
}

#[rstest]
fn grid_sample(graph: &OnnxGraph) {
    let node = find_node(graph, "gridsample");
    insta::assert_snapshot!(format!("{node}"), @r#"
    GridSample "gridsample1"
      Inputs:
        gridsample_input: F32[1, 1, 3, 3]
        gridsample_grid: F32[1, 2, 2, 2]
      Outputs:
        gridsample1_out1: F32[?, ?, ?, ?]
      Config:
        GridSampleConfig {
            mode: Bilinear,
            padding_mode: Zeros,
            align_corners: false,
        }
    "#);
}

#[rstest]
fn is_inf(graph: &OnnxGraph) {
    let node = find_node(graph, "isinf");
    insta::assert_snapshot!(format!("{node}"), @r#"
    IsInf "isinf1"
      Inputs:
        isinf_input: F32[2, 3]
      Outputs:
        isinf1_out1: Bool[?, ?]
      Config:
        IsInfConfig {
            detect_negative: true,
            detect_positive: true,
        }
    "#);
}

#[rstest]
fn is_na_n(graph: &OnnxGraph) {
    let node = find_node(graph, "isnan");
    insta::assert_snapshot!(format!("{node}"), @r#"
    IsNaN "isnan1"
      Inputs:
        isnan_input: F32[2, 3]
      Outputs:
        isnan1_out1: Bool[?, ?]
    "#);
}

#[rstest]
fn reduce_max(graph: &OnnxGraph) {
    let node = find_node(graph, "reducemax");
    insta::assert_snapshot!(format!("{node}"), @r#"
    ReduceMax "reducemax1"
      Inputs:
        reducemax_input: F32[2, 3, 4]
        _: I64[1] [static(1)]
      Outputs:
        reducemax1_out1: F32[2, 1, 4]
      Config:
        ReduceConfig {
            dims: [
                1,
            ],
            keepdims: true,
        }
    "#);
}

#[rstest]
fn reduce_min(graph: &OnnxGraph) {
    let node = find_node(graph, "reducemin");
    insta::assert_snapshot!(format!("{node}"), @r#"
    ReduceMin "reducemin1"
      Inputs:
        reducemin_input: F32[2, 3, 4]
        _: I64[1] [static(2)]
      Outputs:
        reducemin1_out1: F32[2, 1, 4]
      Config:
        ReduceConfig {
            dims: [
                1,
            ],
            keepdims: true,
        }
    "#);
}

