//! Opset 19 compliance tests.
//!
//! Auto-generated by gen_rust_tests.py. Edit the generator, not this file.

use super::helpers::*;
use rstest::*;

#[fixture]
#[once]
fn graph() -> OnnxGraph {
    load_model("opset_19.onnx")
}

#[rstest]
fn average_pool(graph: &OnnxGraph) {
    let node = find_node(graph, "averagepool2d");
    insta::assert_snapshot!(format!("{node}"), @r#"
    AveragePool2d "averagepool2d1"
      Inputs:
        averagepool_input: F32[1, 3, 8, 8]
      Outputs:
        averagepool2d1_out1: F32[?, ?, ?, ?]
      Config:
        AvgPool2dConfig {
            kernel_size: [
                2,
                2,
            ],
            strides: [
                2,
                2,
            ],
            padding: Valid,
            count_include_pad: false,
            dilation: [
                1,
                1,
            ],
            ceil_mode: false,
            auto_pad: NotSet,
        }
    "#);
}

#[rstest]
fn cast(graph: &OnnxGraph) {
    let node = find_node(graph, "cast");
    insta::assert_snapshot!(format!("{node}"), @r#"
    Cast "cast1"
      Inputs:
        cast_input: F32[2, 3]
      Outputs:
        cast1_out1: I32[2, 3]
      Config:
        CastConfig {
            to: I32,
        }
    "#);
}

#[rstest]
fn constant(graph: &OnnxGraph) {
    let node = find_node(graph, "constant");
    insta::assert_snapshot!(format!("{node}"), @r#"
    Constant "constant8"
      Inputs:
        _: F32[2, 3] [static(7)]
      Outputs:
        constant8_out1: F32[2, 3] [constant]
    "#);
}

#[rstest]
fn deform_conv(graph: &OnnxGraph) {
    let node = find_node(graph, "deformconv");
    insta::assert_snapshot!(format!("{node}"), @r#"
    DeformConv "deformconv1"
      Inputs:
        deformconv_input: F32[1, 1, 3, 3]
        _: F32[1, 1, 2, 2] [static(0)]
        deformconv_offset: F32[1, 8, 2, 2]
      Outputs:
        deformconv1_out1: F32[1, 1, 2, 2]
      Config:
        DeformConvConfig {
            kernel_size: [
                2,
                2,
            ],
            stride: [
                1,
                1,
            ],
            padding: Valid,
            dilation: [
                1,
                1,
            ],
            groups: 1,
            offset_groups: 1,
        }
    "#);
}

#[rstest]
fn equal(graph: &OnnxGraph) {
    let node = find_node(graph, "equal");
    insta::assert_snapshot!(format!("{node}"), @r#"
    Equal "equal1"
      Inputs:
        equal_a: F32[2, 3, 4]
        equal_b: F32[2, 3, 4]
      Outputs:
        equal1_out1: Bool[2, 3, 4]
    "#);
}

/// Identity is eliminated during post-processing (no-op).
/// Verify the model parses without error.
#[test]
fn identity() {
    let _graph = load_model("opset_19.onnx");
}

#[rstest]
fn if_op(graph: &OnnxGraph) {
    let node = find_node(graph, "if");
    insta::assert_snapshot!(format!("{node}"), @r#"
    If "if1"
      Inputs:
        if_condition: ScalarNative(Bool)
      Outputs:
        if1_out1: F32[2, 3]
      Config:
        IfConfig {
            then_branch: OnnxGraph {
                nodes: [
                    Constant(
                        ConstantNode {
                            name: "constant12",
                            inputs: [
                                Argument {
                                    name: "",
                                    ty: Tensor(
                                        TensorType {
                                            dtype: F32,
                                            rank: 2,
                                            static_shape: Some(
                                                [
                                                    Some(
                                                        2,
                                                    ),
                                                    Some(
                                                        3,
                                                    ),
                                                ],
                                            ),
                                        },
                                    ),
                                    value_source: Static(
                                        0,
                                    ),
                                },
                            ],
                            outputs: [
                                Argument {
                                    name: "constant12_out1",
                                    ty: Tensor(
                                        TensorType {
                                            dtype: F32,
                                            rank: 2,
                                            static_shape: Some(
                                                [
                                                    Some(
                                                        2,
                                                    ),
                                                    Some(
                                                        3,
                                                    ),
                                                ],
                                            ),
                                        },
                                    ),
                                    value_source: Constant,
                                },
                            ],
                        },
                    ),
                ],
                inputs: [],
                outputs: [
                    Argument {
                        name: "constant12_out1",
                        ty: Tensor(
                            TensorType {
                                dtype: F32,
                                rank: 2,
                                static_shape: Some(
                                    [
                                        Some(
                                            2,
                                        ),
                                        Some(
                                            3,
                                        ),
                                    ],
                                ),
                            },
                        ),
                        value_source: Constant,
                    },
                ],
                value_store: Some(
                    ValueStore {
                        tensor_store: TensorStore {
                            data: {
                                0: TensorDataRef {
                                    shape: [
                                        2,
                                        3,
                                    ],
                                    dtype: F32,
                                    source: Embedded(
                                        b"\0\0\x80?\0\0\x80?\0\0\x80?\0\0\x80?\0\0\x80?\0\0\x80?",
                                    ),
                                },
                            },
                            next_id: 1,
                        },
                        constant_map: {
                            "constant12_out1": 0,
                        },
                    },
                ),
            },
            else_branch: OnnxGraph {
                nodes: [
                    Constant(
                        ConstantNode {
                            name: "constant13",
                            inputs: [
                                Argument {
                                    name: "",
                                    ty: Tensor(
                                        TensorType {
                                            dtype: F32,
                                            rank: 2,
                                            static_shape: Some(
                                                [
                                                    Some(
                                                        2,
                                                    ),
                                                    Some(
                                                        3,
                                                    ),
                                                ],
                                            ),
                                        },
                                    ),
                                    value_source: Static(
                                        0,
                                    ),
                                },
                            ],
                            outputs: [
                                Argument {
                                    name: "constant13_out1",
                                    ty: Tensor(
                                        TensorType {
                                            dtype: F32,
                                            rank: 2,
                                            static_shape: Some(
                                                [
                                                    Some(
                                                        2,
                                                    ),
                                                    Some(
                                                        3,
                                                    ),
                                                ],
                                            ),
                                        },
                                    ),
                                    value_source: Constant,
                                },
                            ],
                        },
                    ),
                ],
                inputs: [],
                outputs: [
                    Argument {
                        name: "constant13_out1",
                        ty: Tensor(
                            TensorType {
                                dtype: F32,
                                rank: 2,
                                static_shape: Some(
                                    [
                                        Some(
                                            2,
                                        ),
                                        Some(
                                            3,
                                        ),
                                    ],
                                ),
                            },
                        ),
                        value_source: Constant,
                    },
                ],
                value_store: Some(
                    ValueStore {
                        tensor_store: TensorStore {
                            data: {
                                0: TensorDataRef {
                                    shape: [
                                        2,
                                        3,
                                    ],
                                    dtype: F32,
                                    source: Embedded(
                                        b"\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0",
                                    ),
                                },
                            },
                            next_id: 1,
                        },
                        constant_map: {
                            "constant13_out1": 0,
                        },
                    },
                ),
            },
            scope_ref_names: [],
        }
    "#);
}

#[rstest]
fn pad(graph: &OnnxGraph) {
    let node = find_node(graph, "pad");
    insta::assert_snapshot!(format!("{node}"), @r#"
    Pad "pad1"
      Inputs:
        pad_input: F32[2, 3]
        _: I64[4] [static(1)]
        _: ScalarNative(F32) [static(2)]
      Outputs:
        pad1_out1: F32[2, 3]
      Config:
        PadConfig {
            pads: Static(
                [
                    (
                        0,
                        0,
                    ),
                    (
                        1,
                        1,
                    ),
                ],
            ),
            constant_value: Static(
                0.0,
            ),
            mode: Constant,
        }
    "#);
}

#[rstest]
fn reshape(graph: &OnnxGraph) {
    let node = find_node(graph, "reshape");
    insta::assert_snapshot!(format!("{node}"), @r#"
    Reshape "reshape1"
      Inputs:
        reshape_input: F32[2, 3, 4]
        _: I64[2] [static(3)]
      Outputs:
        reshape1_out1: F32[6, 4]
      Config:
        ReshapeConfig {
            shape: Static(
                [
                    6,
                    4,
                ],
            ),
        }
    "#);
}

#[rstest]
fn resize(graph: &OnnxGraph) {
    let node = find_node(graph, "resize");
    insta::assert_snapshot!(format!("{node}"), @r#"
    Resize "resize1"
      Inputs:
        resize_input: F32[1, 1, 2, 2]
        _: F32[0] [static(4)]
        _: F32[0] [static(5)]
        _: I64[4] [static(6)]
      Outputs:
        resize1_out1: F32[1, 1, 2, 2]
      Config:
        ResizeConfig {
            mode: Nearest,
            scales: None,
            sizes: Some(
                Static(
                    [
                        4,
                        4,
                    ],
                ),
            ),
            coordinate_transformation_mode: "half_pixel",
            cubic_coeff_a: -0.75,
            nearest_mode: "round_prefer_floor",
            exclude_outside: 0,
            extrapolation_value: 0.0,
            antialias: 0,
        }
    "#);
}

#[rstest]
fn shape(graph: &OnnxGraph) {
    let node = find_node(graph, "shape");
    insta::assert_snapshot!(format!("{node}"), @r#"
    Shape "shape1"
      Inputs:
        shape_input: F32[2, 3, 4]
      Outputs:
        shape1_out1: Shape(3)
      Config:
        ShapeConfig {
            start: 0,
            end: 3,
        }
    "#);
}

#[rstest]
fn size(graph: &OnnxGraph) {
    let node = find_node(graph, "size");
    insta::assert_snapshot!(format!("{node}"), @r#"
    Size "size1"
      Inputs:
        size_input: F32[2, 3, 4]
      Outputs:
        size1_out1: ScalarNative(I64)
    "#);
}
