//! Opset 15 compliance tests.
//!
//! Auto-generated by gen_rust_tests.py. Edit the generator, not this file.

use super::helpers::*;
use rstest::*;

#[fixture]
#[once]
fn graph() -> OnnxGraph {
    load_model("opset_15.onnx")
}

#[rstest]
fn batch_normalization(graph: &OnnxGraph) {
    let node = find_node(graph, "batchnormalization");
    insta::assert_snapshot!(format!("{node}"), @r#"
    BatchNormalization "batchnormalization1"
      Inputs:
        batchnormalization_input: F32[1, 3, 4, 4]
        _: F32[3] [static(0)]
        _: F32[3] [static(1)]
        _: F32[3] [static(2)]
        _: F32[3] [static(3)]
      Outputs:
        batchnormalization1_out1: F32[1, 3, 4, 4]
      Config:
        Static(
            BatchNormStaticConfig {
                epsilon: 0.0,
                momentum: 0.0,
            },
        )
    "#);
}

#[rstest]
fn bernoulli(graph: &OnnxGraph) {
    let node = find_node(graph, "bernoulli");
    insta::assert_snapshot!(format!("{node}"), @r#"
    Bernoulli "bernoulli1"
      Inputs:
        bernoulli_input: F32[2, 3]
      Outputs:
        bernoulli1_out1: F32[2, 3]
    "#);
}

#[rstest]
fn pow(graph: &OnnxGraph) {
    let node = find_node(graph, "pow");
    insta::assert_snapshot!(format!("{node}"), @r#"
    Pow "pow1"
      Inputs:
        pow_a: F32[2, 3, 4]
        pow_b: F32[2, 3, 4]
      Outputs:
        pow1_out1: F32[2, 3, 4]
    "#);
}

#[rstest]
fn shape(graph: &OnnxGraph) {
    let node = find_node(graph, "shape");
    insta::assert_snapshot!(format!("{node}"), @r#"
    Shape "shape1"
      Inputs:
        shape_input: F32[2, 3, 4]
      Outputs:
        shape1_out1: Shape(3)
      Config:
        ShapeConfig {
            start: 0,
            end: 3,
        }
    "#);
}

