//! Opset 5 compliance tests.
//!
//! Auto-generated by gen_rust_tests.py. Edit the generator, not this file.

use super::helpers::*;
use rstest::*;

#[fixture]
#[once]
fn graph() -> OnnxGraph {
    load_model("opset_05.onnx")
}

#[rstest]
fn reshape(graph: &OnnxGraph) {
    let node = find_node(graph, "reshape");
    insta::assert_snapshot!(format!("{node}"), @r#"
    Reshape "reshape1"
      Inputs:
        reshape_input: F32[2, 3, 4]
        _: I64[2] [static(0)]
      Outputs:
        reshape1_out1: F32[6, 4]
      Config:
        ReshapeConfig {
            shape: Static(
                [
                    6,
                    4,
                ],
            ),
        }
    "#);
}

