//! Integration tests for custom (non-built-in) operator parsing.
//!
//! Fixture: `fixtures/custom_ops.onnx`, generated by `scripts/custom_ops.py`.
//! The model contains two identical custom-domain nodes (CSE bait), a custom
//! node with attributes and a constant input, and an unknown op_type in the
//! default ONNX domain.

mod test_utils;

use onnx_ir::CustomNode;
use onnx_ir::ir::Node;
use test_utils::*;

fn custom_nodes(graph: &onnx_ir::ir::OnnxGraph) -> Vec<&CustomNode> {
    graph
        .nodes
        .iter()
        .filter_map(|n| match n {
            Node::Custom(c) => Some(c),
            _ => None,
        })
        .collect()
}

#[test]
fn custom_ops_parse_instead_of_panicking() {
    let graph = load_onnx("custom_ops.onnx");

    let customs = custom_nodes(&graph);
    assert_eq!(
        customs.len(),
        3,
        "expected fft1, fft2, and the unknown default-domain op"
    );

    // Built-in neighbors still resolve normally
    assert_eq!(count_nodes(&graph, |n| matches!(n, Node::Relu(_))), 1);
    assert_eq!(count_nodes(&graph, |n| matches!(n, Node::Add(_))), 1);
}

#[test]
fn custom_domain_identity_and_opset_preserved() {
    let graph = load_onnx("custom_ops.onnx");

    let customs = custom_nodes(&graph);
    let fft = customs
        .iter()
        .find(|c| c.op_type == "FftLike")
        .expect("FftLike node");

    assert_eq!(fft.domain, "my.custom.domain");
    // The custom domain's opset from opset_import, not the default-domain 16
    assert_eq!(fft.opset, 3);
}

#[test]
fn default_domain_unknown_op_uses_default_opset() {
    let graph = load_onnx("custom_ops.onnx");

    let customs = custom_nodes(&graph);
    let unknown = customs
        .iter()
        .find(|c| c.op_type == "MyUnknownOp")
        .expect("MyUnknownOp node");

    assert_eq!(unknown.domain, "");
    assert_eq!(unknown.opset, 16);
}

#[test]
fn custom_op_attributes_are_readable() {
    let graph = load_onnx("custom_ops.onnx");

    let customs = custom_nodes(&graph);
    let fft = customs
        .iter()
        .find(|c| c.op_type == "FftLike")
        .expect("FftLike node");

    assert_eq!(fft.attrs.get_i64("n_fft"), Some(1024));
    assert_eq!(fft.attrs.get_f32("scale"), Some(0.5));
    assert_eq!(fft.attrs.get_string("mode"), Some("real"));
    assert_eq!(fft.attrs.get_i64s("axes"), Some(&[0, 1][..]));
    // Wrong-type and absent lookups return None
    assert_eq!(fft.attrs.get_i64("scale"), None);
    assert_eq!(fft.attrs.get_i64("nonexistent"), None);
}

#[test]
fn custom_op_constant_input_value_is_readable() {
    let graph = load_onnx("custom_ops.onnx");

    let customs = custom_nodes(&graph);
    let fft = customs
        .iter()
        .find(|c| c.op_type == "FftLike")
        .expect("FftLike node");

    // inputs[1] is the "window" initializer; its data must be reachable
    // through the public Argument::value() so future hooks can read it.
    let window = fft.inputs[1]
        .value()
        .expect("constant input value should be readable");
    assert_eq!(window.shape.to_vec(), vec![4]);
    let values = window.to_vec::<f32>().unwrap();
    assert_eq!(values, vec![0.25, 0.5, 0.75, 1.0]);
}

#[test]
fn identical_custom_nodes_are_not_cse_merged() {
    // Simplification (which includes CSE) must keep both FftLike twins:
    // custom op semantics are unknown (possibly stateful or random).
    let graph = load_onnx_simplified("custom_ops.onnx");

    let fft_count = custom_nodes(&graph)
        .iter()
        .filter(|c| c.op_type == "FftLike")
        .count();
    assert_eq!(fft_count, 2, "CSE must not merge identical custom nodes");
}

#[test]
fn fallback_inference_propagates_input_type() {
    let graph = load_onnx("custom_ops.onnx");

    let customs = custom_nodes(&graph);
    let fft = customs
        .iter()
        .find(|c| c.op_type == "FftLike")
        .expect("FftLike node");

    // Without a registered hook, output type falls back to the input type.
    assert_eq!(fft.outputs[0].ty, fft.inputs[0].ty);
}

// ---------------------------------------------------------------------------
// Hook-carrying parses (public with_custom_op_inference API)
// ---------------------------------------------------------------------------

use onnx_ir::ir::{ArgType, DType, TensorType};
use onnx_ir::{CustomOpInference, HookCoverage, MissingReason, ProcessError};
use std::sync::Arc;

fn fixture_path(name: &str) -> std::path::PathBuf {
    std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures")
        .join(name)
}

/// Covers everything; marks outputs with a distinctive F64 type derived from
/// the input rank so tests can prove the hook (not the fallback) ran.
struct MarkerInference;

impl CustomOpInference for MarkerInference {
    fn coverage(&self, _: &str, _: &str, _: usize) -> HookCoverage {
        HookCoverage::Covered
    }

    fn infer(&self, node: &CustomNode) -> Result<Option<Vec<ArgType>>, ProcessError> {
        let rank = match &node.inputs[0].ty {
            ArgType::Tensor(t) => t.rank,
            _ => 1,
        };
        Ok(Some(vec![
            ArgType::Tensor(TensorType::new(
                DType::F64,
                rank,
                None
            ));
            node.outputs.len()
        ]))
    }
}

/// Covers nothing (empty-registry equivalent).
struct NoCoverageInference;

impl CustomOpInference for NoCoverageInference {
    fn coverage(&self, _: &str, _: &str, _: usize) -> HookCoverage {
        HookCoverage::Missing(MissingReason::NoHook)
    }

    fn infer(&self, _: &CustomNode) -> Result<Option<Vec<ArgType>>, ProcessError> {
        Ok(None)
    }
}

#[test]
fn inference_hooks_reach_if_subgraph_bodies() {
    // The custom op lives inside the If node's then-branch; the hook must be
    // carried into the subgraph build via DeferredGraph.
    let graph = onnx_ir::OnnxGraphBuilder::new()
        .simplify(false)
        .with_custom_op_inference(Arc::new(MarkerInference))
        .parse_file(fixture_path("custom_in_if.onnx"))
        .expect("parse with hooks");

    let if_node = graph
        .nodes
        .iter()
        .find_map(|n| match n {
            Node::If(n) => Some(n),
            _ => None,
        })
        .expect("If node");
    let sub_custom = if_node
        .config
        .then_branch
        .nodes
        .iter()
        .find_map(|n| match n {
            Node::Custom(c) => Some(c),
            _ => None,
        })
        .expect("custom node inside then-branch");

    assert!(
        matches!(&sub_custom.outputs[0].ty, ArgType::Tensor(t) if t.dtype == DType::F64),
        "hook-provided type missing inside subgraph: {:?}",
        sub_custom.outputs[0].ty
    );
}

#[test]
fn hooks_and_simplification_compose() {
    // With a covering hook AND simplify on, the CSE twins must still both
    // survive and carry hook-provided types.
    let graph = onnx_ir::OnnxGraphBuilder::new()
        .simplify(true)
        .with_custom_op_inference(Arc::new(MarkerInference))
        .parse_file(fixture_path("custom_ops.onnx"))
        .expect("parse with hooks and simplify");

    let customs = custom_nodes(&graph);
    let ffts: Vec<_> = customs.iter().filter(|c| c.op_type == "FftLike").collect();
    assert_eq!(ffts.len(), 2, "CSE must not merge hooked custom nodes");
    for fft in ffts {
        assert!(
            matches!(&fft.outputs[0].ty, ArgType::Tensor(t) if t.dtype == DType::F64),
            "hook-provided type missing under simplify"
        );
    }
}

#[test]
fn coverage_error_aggregates_node_counts() {
    // The fixture uses FftLike twice; the missing-hook summary must say so.
    let err = onnx_ir::OnnxGraphBuilder::new()
        .with_custom_op_inference(Arc::new(NoCoverageInference))
        .parse_file(fixture_path("custom_ops.onnx"))
        .unwrap_err();

    let msg = format!("{err}");
    assert!(
        msg.contains("my.custom.domain::FftLike used by 2 node(s)"),
        "got: {msg}"
    );
    assert!(msg.contains("MyUnknownOp used by 1 node(s)"), "got: {msg}");
}
